More realistic ore gen
UVSE-Invictus/invictus pull request #35
Opened 2024-05-04 03:33 UTC by Bt111488

Merge Ore gen Into main, numbers should not change untill testing stage feed back

2024-05-04 03:35 UTC, Bt111488 commented
Adds all the custom orgen needed that I know of, and numbers are steady untill feedback in testing

2024-05-04 06:12 UTC, SLimeyMC commented
This seems to solve #14 so that;s great. however I noticed that you're using custom ores? please use Minecraft equivalent of it, since it will be harder to integrate with the nature of the modpack being create themed

2024-05-04 14:45 UTC, Bt111488 commented
The custom ores are all forge tagged as they are added by the ore generation mod, but if you still want me to go back and replace all of them with others I can, it will just take time, also multiple of the ores can already be interacted with by create due to the forge tags

2024-05-04 15:14 UTC, SLimeyMC commented
No, but the nature of the pack being create which resolve around being create friendly. the ore just doesn't fit right in especially with the custom pack we have

2024-05-04 15:18 UTC, SLimeyMC commented
Also i tried launching the branch, it crashed...

2024-05-04 16:40 UTC, Bt111488 commented
Alright, I will change out the ores, it will just take some time.

2024-06-06 03:31 UTC, SLimeyMC requested changes
It have pretty inconsistent ore selection, some weird comment that frankly I don't think it work in json. You might also replace the name of the json file to the actual ore and it's modifier like coal_abundance , coal_dike or whatever. You should also remove the markdown text that isn't used anymore

2024-06-06 03:31 UTC, SLimeyMC commented on config/global_data_and_resourcepacks.toml
I think you should just put custom oregen on `global_packs/required_data/`, and also use snake_case instead of that something like `custom_oregen_v1`

2024-06-06 03:31 UTC, SLimeyMC commented on mods/yungs-api.pw.toml
What's the YUNGS api for?

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/ore/INPROGRESSORES.txt
Can you remove this file?

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/ore/autunite.json
What Autunite supposed to be?

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/ore/bauxite.json
There is comented braces?

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/ore/beryl.json
I dont think we use Beryl

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/ore/cassiterite.json
Replace these with create tin

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/ore/galena.json
These, i don't think we use lead, Mekanism is locked

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/ore/limonite.json
Replace this with iron ore

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/ore/platinum.json
use create tin, it work well with the resourcepack

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/ore/sphalerite.json
Remove this file then

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/ore/teallite_and_emerald.json
Commented braces? and also teallite and beryl, replace or remove it

2024-06-06 03:31 UTC, SLimeyMC commented on resourcepacks/Custom_OregenV1/data/geolosys/deposits/other/peat.json
What peat supposed to be?

2024-06-06 04:38 UTC, Bt111488 commented
All of these file names must exist in the pack, otherwise it will auto generate the files, but commenting out the files stop the files from reading, meaning it will not generate that file, but it also will not generate that ore

2024-06-06 04:39 UTC, Bt111488 commented
however I may be able to just comment out all of the base files and just do all completly custom files

2024-06-06 05:06 UTC, Bt111488 commented
Now all the ores are under their own files and the defaults are disabled

2024-06-06 05:08 UTC, SLimeyMC commented
Alright good enough merging :+1:

2024-06-06 05:08 UTC, merged